import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Homepage/NavbarDemo.";
const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "@/components/Homepage/theme-provider";
import Footer from "@/components/Homepage/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} bg-black  text-white overflow-x-hidden`}
      >
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
